name: flutter_quill_test
description: Test utilities for flutter_quill which includes methods to simplify interacting with the editor in test cases.
version: 0.0.5
homepage: https://1o24bbs.com/c/bulletjournal/108
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_test

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
 - quill

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.0 <3.16.0"
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: 8.6.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
