name: delta_markdown_converter
version: 0.0.2

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/freshtechtips/delta_markdown_converter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.0 <3.16.0"
  flutter: 3.16.0

dependencies:
  args: ^2.4.2
  charcode: ^1.3.1
  collection: ^1.15.0
  flutter_quill: ^8.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.3
